import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import digimonList from "../json/digimonList.json";
import Card from "@/component/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const babyDigimonList = digimonList.filter((digimon) => digimon.level === 1);

  console.log(digimonList.sort((a, b) => a.id - b.id));

  function findEvolutions(ids: number[] | never[]) {
    return ids.map((id) => {
      if (!id || id >= 1000) {
        return;
      }

      return digimonList.find((digimon) => digimon.id === id);
    });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{ paddingBottom: "2rem" }}>
          <div>
            {babyDigimonList.map((digimon1) => {
              return (
                <div style={{ display: "flex" }} key={digimon1.id}>
                  <Card evolutionChart digimon={digimon1} />
                  {digimon1.evolveTo.length > 0 && (
                    <div
                      style={{
                        display: "flex",
                        flexDirection: "column",
                      }}
                    >
                      {findEvolutions(digimon1.evolveTo).map((digimon2) => {
                        if (digimon2 === undefined) {
                          return;
                        }

                        return (
                          <div key={digimon2.id} style={{ display: "flex" }}>
                            <Card evolutionChart digimon={digimon2} />
                            {digimon2.evolveTo.length > 0 && (
                              <div>
                                {findEvolutions(digimon2.evolveTo).map(
                                  (digimon3) => {
                                    if (digimon3 === undefined) {
                                      return;
                                    }
                                    return (
                                      <div
                                        key={digimon3.id}
                                        style={{
                                          display: "flex",
                                        }}
                                      >
                                        <Card
                                          evolutionChart
                                          digimon={digimon3}
                                        />
                                        {digimon3.evolveTo.length > 0 && (
                                          <div>
                                            {findEvolutions(
                                              digimon3.evolveTo
                                            ).map((digimon4) => {
                                              if (digimon4 === undefined) {
                                                return;
                                              }
                                              return (
                                                <div
                                                  key={digimon4.id}
                                                  style={{
                                                    display: "flex",
                                                  }}
                                                >
                                                  <Card
                                                    evolutionChart
                                                    digimon={digimon4}
                                                  />
                                                  {digimon4.evolveTo.length >
                                                    0 && (
                                                    <div>
                                                      {findEvolutions(
                                                        digimon4.evolveTo
                                                      ).map((digimon5) => {
                                                        if (
                                                          digimon5 === undefined
                                                        ) {
                                                          return;
                                                        }

                                                        //incio
                                                        // return (
                                                        //   <Card evolutionChart
                                                        //     digimon={digimon5}
                                                        //   />
                                                        // );
                                                        return (
                                                          <div
                                                            key={digimon5.id}
                                                            style={{
                                                              display: "flex",
                                                            }}
                                                          >
                                                            <Card
                                                              evolutionChart
                                                              digimon={digimon5}
                                                            />
                                                            {digimon5.evolveTo
                                                              .length > 0 && (
                                                              <div>
                                                                {findEvolutions(
                                                                  digimon5.evolveTo
                                                                ).map(
                                                                  (
                                                                    digimon6
                                                                  ) => {
                                                                    if (
                                                                      digimon6 ===
                                                                      undefined
                                                                    ) {
                                                                      return;
                                                                    }
                                                                    //i
                                                                    // return (
                                                                    //   <Card evolutionChart
                                                                    //     digimon={
                                                                    //       digimon6
                                                                    //     }
                                                                    //   />
                                                                    // );
                                                                    return (
                                                                      <div
                                                                        key={
                                                                          digimon6.id
                                                                        }
                                                                        style={{
                                                                          display:
                                                                            "flex",
                                                                        }}
                                                                      >
                                                                        <Card
                                                                          evolutionChart
                                                                          digimon={
                                                                            digimon6
                                                                          }
                                                                        />
                                                                        {digimon6
                                                                          .evolveTo
                                                                          .length >
                                                                          0 && (
                                                                          <div>
                                                                            {findEvolutions(
                                                                              digimon6.evolveTo
                                                                            ).map(
                                                                              (
                                                                                digimon7
                                                                              ) => {
                                                                                if (
                                                                                  digimon7 ===
                                                                                  undefined
                                                                                ) {
                                                                                  return;
                                                                                }

                                                                                return (
                                                                                  <Card
                                                                                    evolutionChart
                                                                                    digimon={
                                                                                      digimon7
                                                                                    }
                                                                                  />
                                                                                );
                                                                              }
                                                                            )}
                                                                          </div>
                                                                        )}
                                                                      </div>
                                                                    );
                                                                    //f
                                                                  }
                                                                )}
                                                              </div>
                                                            )}
                                                          </div>
                                                        );
                                                        //fim
                                                      })}
                                                    </div>
                                                  )}
                                                </div>
                                              );
                                            })}
                                          </div>
                                        )}
                                      </div>
                                    );
                                  }
                                )}
                              </div>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
