import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import digimonList from "../json/digimonList.json";
import Card from "@/component/Card";
import Group from "@/component/Group";

const inter = Inter({ subsets: ["latin"] });

export default function List() {
  const babyDigimonList = digimonList.filter((digimon) => digimon.level === 1);
  const inTrainingDigimonList = digimonList.filter(
    (digimon) => digimon.level === 2
  );
  const rookieDigimonList = digimonList.filter(
    (digimon) => digimon.level === 3
  );
  const adultDigimonList = digimonList.filter((digimon) => digimon.level === 4);
  const perfectDigimonList = digimonList.filter(
    (digimon) => digimon.level === 5
  );
  const ultimateDigimonList = digimonList.filter(
    (digimon) => digimon.level === 6
  );
  const superUltimateDigimonList = digimonList.filter(
    (digimon) => digimon.level === 7
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{ paddingBottom: "2rem" }}>
          {babyDigimonList.length > 0 && (
            <Group name="Baby Level" list={babyDigimonList} />
          )}
        </div>
      </main>
    </>
  );
}
